# Generated by Django 4.2.16 on 2024-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "registered_address_town",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("company_summary", models.TextField(blank=True, null=True)),
                ("revenue", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "registered_address_postcode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("do_not_contact_status", models.BooleanField(default=False)),
            ],
        ),
    ]
